editor-app:
  image: localhost:49000/editor:latest
  volumes:
    - /vagrant/editor/app:/opt/app
    # FIXME failed service started...
    # - /vagrant/editor/.docker:/var/lib/docker
  privileged: true
  # ports: nothing XXX Using ephemeral port range. Defaults (32768 - 61000)
  ports:
    - 8080:80

