app:
  container_name: editor-app
  image: localhost:49000/editor-app:latest
  privileged: true
  volumes:
    # application-root
    - ~/editor/app:/opt/app
    # Expose application log
    - /var/log/app
    # docker-compose for Container from host
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
  ports:
    - 8080:80
  environment:
    PORT: 80
    MAIN_SCRIPT: /opt/app/_editor/app/server.js
