editor-app:
  container_name: editor-app
  image: localhost:49000/editor-app:latest
  privileged: true
  volumes:
    # docker for Container from Ubuntu 14.04 host
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/lib/x86_64-linux-gnu/libapparmor.so.1:/usr/lib/x86_64-linux-gnu/libapparmor.so.1
    - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    - /lib/x86_64-linux-gnu/libsystemd-journal.so.0:/lib/x86_64-linux-gnu/libsystemd-journal.so.0
    - /lib/x86_64-linux-gnu/libcgmanager.so.0:/lib/x86_64-linux-gnu/libcgmanager.so.0
    - /lib/x86_64-linux-gnu/libnih.so.1:/lib/x86_64-linux-gnu/libnih.so.1
    - /lib/x86_64-linux-gnu/libnih-dbus.so.1:/lib/x86_64-linux-gnu/libnih-dbus.so.1
    - /lib/x86_64-linux-gnu/libdbus-1.so.3:/lib/x86_64-linux-gnu/libdbus-1.so.3
    - /lib/x86_64-linux-gnu/libgcrypt.so.11:/lib/x86_64-linux-gnu/libgcrypt.so.11
    # docker-compose for Container from host
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    # Expose application log
    - /var/log/app
    # application-root
    - /vagrant/editor/app:/opt/app
  ports:
    - 8080:80
  environment:
    ENV: local
    PORT: 80
    MAIN_SCRIPT: /opt/app/_editor/app/server.js

editor-log:
  container_name: editor-log
  image: localhost:49000/editor-log:latest
  ports:
    - 18082:8080
  volumes:
    - /vagrant/editor/app/log/app/etc/fluent-log.conf:/fluentd/etc/fluent-log.conf
  volumes_from:
    - editor-app
  environment:
    FLUENTD_CONF: fluent-log.conf

# editor-be:
#   container_name: editor-be
#   image: localhost:49000/editor-be:latest
#   ports:
#     - 6379:6379
#   environment:
#     xxxx: xxxx

editor-md:
  container_name: editor-md
  image: localhost:49000/editor-md:latest
  volumes:
    - /vagrant/editor/app/md/app:/opt/app
  ports:
    - 18081:80
    # - 3306:3306
  environment:
    MAIN_SCRIPT: /opt/app/server.js
    PORT: 80
    MYSQL_USER: user
    MYSQL_PASSWORD: password
