editor-app:
  container_name: editor-app
  image: localhost:49000/editor-app:latest
  privileged: true
  volumes:
    - ~/editor/app:/opt/app
    # docker for Container from CentOS7 host
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
    - /usr/lib64/libltdl.so.7:/usr/lib/libltdl.so.7
    # docker-compose for Container from host
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    # Expose application log
    - /var/log/app
  ports:
    - 8080:80
  environment:
    PORT: 80
    MAIN_SCRIPT: /opt/app/_editor/app/server.js

# editor-log:
#   container_name: editor-log
#   image: editor-log:latest
#   volumes:
#     - ~/editor/app/log/etc:/fluent/etc
#   links:
#     - editor-app
