version: '2'
services:
  webpack:
    container_name: editor-webpack
    image: editor-webpack:latest
    build: ../app/docker/webpack
    volumes:
      - ../app/app:/opt
    command: 'npm run build'
