editor-app:
  extends:
    file: ../app.yml
    service: app
  volumes:
    # docker for Container from AmazonLinux host
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
    - /lib64/libudev.so.0:/usr/lib/libudev.so.0
  environment:
    ENV: aws

editor-log:
  extends:
    file: ../log.yml
    service: log
  volumes_from:
    - editor-app

# editor-db:
#   extends:
#     file: ../db.yml
#     service: db

# editor-md:
#   extends:
#     file: ../md.yml
#     service: md
#   links:
#     - editor-db
