editor-app:
  container_name: editor-app
  image: localhost:49000/editor-app:latest
  privileged: true
  volumes:
    # docker for Container from CentOS7 host
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /lib64/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
    - /lib64/libudev.so.0:/usr/lib/libudev.so.0
    # docker-compose for Container from host
    - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    # Expose application log
    - /var/log/app
    # application-root
    - ~/editor/app:/opt/app
  ports:
    - 8080:80
  environment:
    ENV: aws
    PORT: 80
    MAIN_SCRIPT: /opt/app/_editor/app/server.js

editor-log:
  container_name: editor-log
  image: localhost:49000/editor-log:latest
  ports:
    - 18082:8080
  volumes_from:
    - editor-app

editor-md:
  container_name: editor-md
  image: localhost:49000/editor-md:latest
  volumes:
    - ~/editor/app/md/app:/opt/app
  ports:
    - "18081:80"
    # - "3306:3306"
  environment:
    MAIN_SCRIPT: /opt/app/server.js
    PORT: 80
    MYSQL_USER: user
    MYSQL_PASSWORD: password
